graphiteReporterConfiguration:
  graphiteHost: localhost
  graphitePort: 2003
  reportingIntervalInSeconds : 60
  reportingEnabled: false
  reportingPrefix: "Demo"

adminUserConfiguration:
  username: "admin"
  password: "admin123"
